# Generated by Django 2.1.7 on 2019-03-05 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorium',
            name='capacity',
            field=models.IntegerField(max_length=1000, verbose_name='Capacity'),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='number',
            field=models.IntegerField(max_length=1000, unique=True, verbose_name='Auditorium number'),
        ),
        migrations.AlterField(
            model_name='course',
            name='n_students',
            field=models.IntegerField(max_length=1000, verbose_name='Number of Students'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='Surname'),
        ),
    ]
