# Generated by Django 2.1.7 on 2019-04-16 06:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalproperties',
            name='max_class_in_row',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='type',
            field=models.CharField(choices=[('Prof', 'Professor'), ('TA', 'Teacher Assistant')], default='TA', max_length=4),
            preserve_default=False,
        ),
    ]
