# Generated by Django 2.1.7 on 2019-04-16 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20190416_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.TimeSlot'),
        ),
    ]
