# Generated by Django 2.1.7 on 2019-04-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20190418_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='preferred_day',
        ),
        migrations.AddField(
            model_name='preferences',
            name='preferred_days',
            field=models.CharField(default='Monday, Tuesday', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preferences',
            name='preferred_class_time',
            field=models.CharField(max_length=8),
        ),
    ]
