# Generated by Django 2.1.7 on 2019-03-05 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20190305_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='n_students',
        ),
        migrations.AddField(
            model_name='course',
            name='n_lab',
            field=models.IntegerField(default=100, max_length=1000, verbose_name='Number of students on labs'),
        ),
        migrations.AddField(
            model_name='course',
            name='n_lecture',
            field=models.IntegerField(default=100, max_length=1000, verbose_name='Number of students on lectures'),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='capacity',
            field=models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(100)], verbose_name='Capacity'),
        ),
    ]
