# Generated by Django 2.1.7 on 2019-03-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20190305_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course',
            field=models.CharField(default='Course', max_length=50, unique=True, verbose_name='Course'),
        ),
    ]
