# Generated by Django 2.1.7 on 2019-04-19 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20190418_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='day',
        ),
    ]
