# Generated by Django 2.1.7 on 2019-04-01 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20190401_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('faculty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db.Faculty')),
            ],
            bases=('db.faculty',),
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TA',
            fields=[
                ('faculty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db.Faculty')),
            ],
            bases=('db.faculty',),
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='type',
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.IntegerField(default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='professors',
            field=models.ManyToManyField(to='db.Prof'),
        ),
        migrations.AddField(
            model_name='course',
            name='tas',
            field=models.ManyToManyField(to='db.TA'),
        ),
    ]
