# Generated by Django 2.1.7 on 2019-04-20 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_remove_timeslot_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='num',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
